package io.yamsergey.dta.tools.android.runner;

import io.yamsergey.dta.tools.android.inspect.compose.SidekickConnectionManager;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.regex.*;
import java.util.stream.Stream;

/**
 * Builds, installs, and launches an Android app with dta-sidekick auto-injected.
 *
 * <p>Uses a Gradle init script to inject the sidekick dependency without modifying
 * project files, then installs the APK and launches the main activity.</p>
 */
public class AppRunner {

    private static final Logger log = LoggerFactory.getLogger(AppRunner.class);
    private static final String SIDEKICK_VERSION = "0.9.31";

    public record RunRequest(
        String projectPath,
        String device,
        String variant,
        String module
    ) {
        public RunRequest {
            if (projectPath == null || projectPath.isEmpty()) throw new IllegalArgumentException("projectPath required");
            if (variant == null || variant.isEmpty()) variant = "debug";
            if (module == null || module.isEmpty()) module = ":app";
        }
    }

    public record RunResult(
        boolean success,
        String packageName,
        String apkPath,
        String buildLog,
        String launchActivity,
        String error
    ) {
        public static RunResult failure(String error, String buildLog) {
            return new RunResult(false, null, null, buildLog, null, error);
        }
    }

    public interface ProgressListener {
        void onProgress(String stage, String message);
    }

    private final SidekickConnectionManager connectionManager = SidekickConnectionManager.getInstance();

    public RunResult run(RunRequest request, ProgressListener listener) {
        StringBuilder buildLog = new StringBuilder();

        try {
            // 1. Generate init script
            progress(listener, "INIT_SCRIPT", "Generating sidekick init script...");
            File initScript = generateInitScript(request.variant());
            log.info("Init script: {}", initScript.getAbsolutePath());

            // 2. Build
            progress(listener, "BUILD", "Building " + request.module() + " [" + request.variant() + "]...");
            int exitCode = runGradleBuild(request.projectPath(), request.module(),
                request.variant(), initScript, buildLog, listener);
            if (exitCode != 0) {
                return RunResult.failure("Gradle build failed (exit code " + exitCode + ")", buildLog.toString());
            }

            // 3. Find APK
            progress(listener, "APK_DISCOVERY", "Locating APK...");
            String apkPath = findApk(request.projectPath(), request.module(), request.variant());
            if (apkPath == null) {
                return RunResult.failure("Could not find APK for variant " + request.variant(), buildLog.toString());
            }
            log.info("APK found: {}", apkPath);

            // 4. Get package name
            String packageName = discoverPackageName(apkPath);
            log.info("Package: {}", packageName);

            // 5. Install
            progress(listener, "INSTALL", "Installing " + packageName + "...");
            connectionManager.installApk(request.device(), apkPath);

            // 6. Launch
            progress(listener, "LAUNCH", "Launching " + packageName + "...");
            String component = connectionManager.resolveMainActivity(request.device(), packageName);
            connectionManager.launchActivity(request.device(), component);
            log.info("Launched: {}", component);

            return new RunResult(true, packageName, apkPath, buildLog.toString(), component, null);

        } catch (Exception e) {
            log.error("Run failed: {}", e.getMessage(), e);
            return RunResult.failure(e.getMessage(), buildLog.toString());
        }
    }

    // ========================================================================
    // Init script generation
    // ========================================================================

    File generateInitScript(String variant) throws IOException {
        // Always use debugImplementation — sidekick requires a debuggable build
        // (uses JVMTI hooks). This covers all debug variants: debug, stagingDebug, etc.
        String script = """
            // Auto-generated by DTA
            beforeSettings {
                it.dependencyResolutionManagement {
                    repositories {
                        mavenCentral()
                    }
                }
            }
            allprojects {
                afterEvaluate {
                    if (plugins.hasPlugin('com.android.application') || plugins.hasPlugin('com.android.library')) {
                        dependencies {
                            debugImplementation 'io.github.yamsergey:dta-sidekick:%s'
                        }
                        logger.lifecycle("[DTA] Injected dta-sidekick:%s into ${project.name} [%s]")
                    }
                }
            }
            """.formatted(SIDEKICK_VERSION, SIDEKICK_VERSION, variant);

        File tmpFile = File.createTempFile("dta-sidekick-inject-", ".gradle");
        tmpFile.deleteOnExit();
        Files.writeString(tmpFile.toPath(), script);
        return tmpFile;
    }

    // ========================================================================
    // Gradle build
    // ========================================================================

    private int runGradleBuild(String projectPath, String module, String variant,
                               File initScript, StringBuilder buildLog,
                               ProgressListener listener) throws IOException, InterruptedException {
        Path projectDir = Path.of(projectPath);
        String gradlew = findGradlew(projectDir);

        // assemble{Variant} with first letter capitalized
        String taskName = module + ":assemble" + capitalize(variant);

        List<String> cmd = new ArrayList<>();
        cmd.add(gradlew);
        cmd.add(taskName);
        cmd.add("--init-script");
        cmd.add(initScript.getAbsolutePath());

        log.info("Gradle command: {}", String.join(" ", cmd));

        ProcessBuilder pb = new ProcessBuilder(cmd);
        pb.directory(projectDir.toFile());
        pb.redirectErrorStream(true);
        Process process = pb.start();

        // Stream output
        try (BufferedReader reader = new BufferedReader(
                new InputStreamReader(process.getInputStream(), StandardCharsets.UTF_8))) {
            String line;
            while ((line = reader.readLine()) != null) {
                buildLog.append(line).append('\n');
                progress(listener, "BUILD", line);
            }
        }

        boolean finished = process.waitFor(10, TimeUnit.MINUTES);
        if (!finished) {
            process.destroyForcibly();
            throw new IOException("Gradle build timed out after 10 minutes");
        }
        return process.exitValue();
    }

    private String findGradlew(Path projectDir) throws IOException {
        boolean isWindows = System.getProperty("os.name").toLowerCase().contains("win");
        String name = isWindows ? "gradlew.bat" : "gradlew";
        Path gradlew = projectDir.resolve(name);
        if (!Files.isExecutable(gradlew)) {
            throw new IOException("Gradle wrapper not found or not executable: " + gradlew);
        }
        return gradlew.toAbsolutePath().toString();
    }

    // ========================================================================
    // APK discovery
    // ========================================================================

    String findApk(String projectPath, String module, String variant) throws IOException {
        // Module ":app" -> "app", ":feature:detail" -> "feature/detail"
        String modulePath = module.replaceFirst("^:", "").replace(':', '/');
        Path outputDir = Path.of(projectPath, modulePath, "build", "outputs", "apk");

        if (!Files.isDirectory(outputDir)) {
            return null;
        }

        // Search for APKs matching the variant
        try (Stream<Path> walk = Files.walk(outputDir, 4)) {
            return walk
                .filter(p -> p.toString().endsWith(".apk"))
                .filter(p -> !p.getFileName().toString().contains("androidTest"))
                .filter(p -> {
                    // Match variant in path: debug/app-debug.apk or staging/debug/app-staging-debug.apk
                    String rel = outputDir.relativize(p).toString().toLowerCase();
                    return rel.contains(variant.toLowerCase());
                })
                .map(Path::toAbsolutePath)
                .map(Path::toString)
                .findFirst()
                .orElse(null);
        }
    }

    // ========================================================================
    // Package name discovery
    // ========================================================================

    String discoverPackageName(String apkPath) throws IOException, InterruptedException {
        String aapt2 = findAapt2();

        ProcessBuilder pb = new ProcessBuilder(aapt2, "dump", "badging", apkPath);
        pb.redirectErrorStream(true);
        Process process = pb.start();

        String output = new String(process.getInputStream().readAllBytes(), StandardCharsets.UTF_8);
        boolean finished = process.waitFor(30, TimeUnit.SECONDS);
        if (!finished) {
            process.destroyForcibly();
            throw new IOException("aapt2 timed out");
        }

        // Parse: package: name='com.example.app' ...
        Matcher m = Pattern.compile("package:\\s+name='([^']+)'").matcher(output);
        if (m.find()) {
            return m.group(1);
        }
        throw new IOException("Could not parse package name from aapt2 output");
    }

    private String findAapt2() throws IOException {
        // Check ANDROID_HOME
        for (String envVar : new String[]{"ANDROID_HOME", "ANDROID_SDK_ROOT"}) {
            String sdk = System.getenv(envVar);
            if (sdk != null && !sdk.isEmpty()) {
                String aapt2 = findAapt2InSdk(sdk);
                if (aapt2 != null) return aapt2;
            }
        }
        // Common locations
        String home = System.getProperty("user.home");
        for (String rel : new String[]{
                "Library/Android/sdk",   // macOS
                "Android/Sdk",           // Linux
        }) {
            String aapt2 = findAapt2InSdk(Path.of(home, rel).toString());
            if (aapt2 != null) return aapt2;
        }
        // Fallback to PATH
        return "aapt2";
    }

    private String findAapt2InSdk(String sdkPath) {
        Path buildTools = Path.of(sdkPath, "build-tools");
        if (!Files.isDirectory(buildTools)) return null;
        try (Stream<Path> dirs = Files.list(buildTools)) {
            return dirs
                .filter(Files::isDirectory)
                .sorted(Comparator.reverseOrder()) // latest version first
                .map(d -> d.resolve("aapt2"))
                .filter(Files::isExecutable)
                .map(Path::toString)
                .findFirst()
                .orElse(null);
        } catch (IOException e) {
            return null;
        }
    }

    // ========================================================================
    // Helpers
    // ========================================================================

    private static String capitalize(String s) {
        if (s == null || s.isEmpty()) return s;
        return Character.toUpperCase(s.charAt(0)) + s.substring(1);
    }

    private static void progress(ProgressListener listener, String stage, String message) {
        if (listener != null) {
            listener.onProgress(stage, message);
        }
    }
}
