package io.yamsergey.dta.sidekick.compose;

import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicIntegerArray;

/**
 * Tracks recomposition counts and skip counts per composable.
 *
 * <p>This singleton is populated by JVMTI hooks on {@code ComposerImpl.startRestartGroup(int)}
 * and {@code ComposerImpl.skipToGroupEnd()}. The key parameter identifies the composable's
 * source location (generated by the Compose compiler).</p>
 *
 * <p>During the layout tree walk, {@code ComposeInspector} looks up counts by key
 * (matching {@code CompositionGroup.getKey()}) and includes them in the JSON response.</p>
 */
public final class RecompositionTracker {

    // key (from startRestartGroup) → [recomposeCount, skipCount]
    // Using AtomicIntegerArray for thread-safe increments without synchronization
    private static final ConcurrentHashMap<Integer, AtomicIntegerArray> counts = new ConcurrentHashMap<>();

    // Track current restart group key per thread (set by startRestartGroup, read by skipToGroupEnd)
    private static final ThreadLocal<Integer> currentKey = new ThreadLocal<>();

    private RecompositionTracker() {}

    /**
     * Called from the JVMTI hook on {@code ComposerImpl.startRestartGroup(int key)}.
     * Records that a composable with this key is being recomposed.
     */
    public static void onStartRestartGroup(int key) {
        currentKey.set(key);
        counts.computeIfAbsent(key, k -> new AtomicIntegerArray(2)).incrementAndGet(0);
    }

    /**
     * Called from the JVMTI hook on {@code ComposerImpl.skipToGroupEnd()}.
     * Records that the current composable was skipped (not recomposed).
     */
    public static void onSkipToGroupEnd() {
        Integer key = currentKey.get();
        if (key != null) {
            AtomicIntegerArray data = counts.get(key);
            if (data != null) {
                data.decrementAndGet(0); // undo the count from startRestartGroup
                data.incrementAndGet(1); // skips++
            }
        }
    }

    /**
     * Gets the recomposition counts for a composable key.
     *
     * @param key the composable key (from startRestartGroup / CompositionGroup.getKey())
     * @return [recomposeCount, skipCount], or null if no data
     */
    public static int[] getCounts(int key) {
        AtomicIntegerArray data = counts.get(key);
        if (data == null) return null;
        return new int[] { data.get(0), data.get(1) };
    }

    /**
     * Resets all recomposition counts.
     */
    public static void reset() {
        counts.clear();
    }

    /**
     * Returns the number of tracked composable keys.
     */
    public static int getTrackedKeyCount() {
        return counts.size();
    }
}
