package io.yamsergey.dta.sidekick;

import java.io.InputStream;
import java.util.Properties;

/**
 * Reads the sidekick AAR's published version from
 * {@code version.properties} (generated by the build).
 *
 * <p>Centralised so callers don't duplicate the resource lookup.
 * Used in HTTP {@code /health} responses and in the interceptor
 * "installed" log entry — agents can see at a glance what AAR
 * version the host app shipped with, which catches the silent
 * failure mode where an old AAR is bundled and a feature behaves
 * unexpectedly.</p>
 */
public final class SidekickVersion {

    private static final String VALUE = load();

    private SidekickVersion() {}

    public static String get() {
        return VALUE;
    }

    private static String load() {
        try (InputStream is = SidekickVersion.class.getResourceAsStream("/version.properties")) {
            if (is != null) {
                Properties props = new Properties();
                props.load(is);
                return props.getProperty("version", "unknown");
            }
        } catch (Exception ignored) {
            // Best-effort — failing to read the version is not fatal.
        }
        return "unknown";
    }
}
