package io.yamsergey.dta.plugin

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.externalSystem.model.task.ExternalSystemTaskId
import org.gradle.util.GradleVersion
import org.jetbrains.plugins.gradle.service.task.GradleTaskManagerExtension
import org.jetbrains.plugins.gradle.settings.GradleExecutionSettings
import java.io.File

/**
 * Injects dta-sidekick dependency into Android debug builds by adding
 * --init-script to Gradle invocations from Android Studio.
 *
 * No project files are modified — the init script is passed as a
 * command-line argument only when the DTA plugin is active.
 */
class SidekickInjector : GradleTaskManagerExtension {

    private val log = Logger.getInstance(SidekickInjector::class.java)

    override fun configureTasks(
        projectPath: String,
        id: ExternalSystemTaskId,
        settings: GradleExecutionSettings,
        gradleVersion: GradleVersion?
    ) {
        if (enabled) {
            val initScript = getOrCreateInitScript()
            if (initScript != null) {
                settings.withArguments("--init-script", initScript.absolutePath)
                log.info("Injected dta-sidekick init script for tasks in: $projectPath")
            }
        }
    }

    companion object {
        private val log = Logger.getInstance(SidekickInjector::class.java)

        private const val SIDEKICK_VERSION = "0.9.31"

        @Volatile
        var enabled: Boolean = true

        private var cachedInitScript: File? = null

        fun toggle(): Boolean {
            enabled = !enabled
            log.info("Sidekick injection ${if (enabled) "enabled" else "disabled"}")
            return enabled
        }

        private fun getOrCreateInitScript(): File? {
            cachedInitScript?.let { if (it.exists()) return it }

            return try {
                val tmpFile = File.createTempFile("dta-sidekick-inject", ".gradle").apply {
                    deleteOnExit()
                    writeText(buildInitScript())
                }
                cachedInitScript = tmpFile
                tmpFile
            } catch (e: Exception) {
                log.warn("Failed to create init script", e)
                null
            }
        }

        private fun buildInitScript(): String = """
            // Auto-generated by DTA Android Studio Plugin
            beforeSettings {
                it.dependencyResolutionManagement {
                    repositories {
                        mavenCentral()
                    }
                }
            }
            allprojects {
                afterEvaluate {
                    if (plugins.hasPlugin('com.android.application') || plugins.hasPlugin('com.android.library')) {
                        dependencies {
                            debugImplementation 'io.github.yamsergey:dta-sidekick:$SIDEKICK_VERSION'
                        }
                        logger.lifecycle("[DTA] Injected dta-sidekick:$SIDEKICK_VERSION into ${'$'}{project.name} debug build")
                    }
                }
            }
        """.trimIndent()
    }
}
