package io.yamsergey.dta.plugin

import com.intellij.openapi.diagnostic.Logger
import com.intellij.openapi.externalSystem.model.task.ExternalSystemTaskId
import com.intellij.openapi.externalSystem.model.task.ExternalSystemTaskNotificationListener
import org.gradle.util.GradleVersion
import org.jetbrains.plugins.gradle.service.task.GradleTaskManagerExtension
import org.jetbrains.plugins.gradle.settings.GradleExecutionSettings
import java.io.File

/**
 * Injects dta-sidekick dependency into Android debug builds by adding
 * --init-script to Gradle invocations from Android Studio.
 *
 * No project files are modified — the init script is passed as a
 * command-line argument only when the DTA plugin is active.
 */
class SidekickInjector : GradleTaskManagerExtension {

    private val log = Logger.getInstance(SidekickInjector::class.java)

    override fun cancelTask(
        id: ExternalSystemTaskId,
        listener: ExternalSystemTaskNotificationListener
    ): Boolean = false

    override fun configureTasks(
        projectPath: String,
        id: ExternalSystemTaskId,
        settings: GradleExecutionSettings,
        gradleVersion: GradleVersion?
    ) {
        if (enabled) {
            val initScript = getOrCreateInitScript()
            if (initScript != null) {
                settings.withArguments("--init-script", initScript.absolutePath)
                log.info("Injected dta-sidekick init script for tasks in: $projectPath")
            }
        }
    }

    companion object {
        private val log = Logger.getInstance(SidekickInjector::class.java)

        private val SIDEKICK_VERSION: String by lazy { readSidekickVersion() }

        @Volatile
        var enabled: Boolean = true

        private var cachedInitScript: File? = null

        private fun readSidekickVersion(): String {
            try {
                val props = java.util.Properties()
                SidekickInjector::class.java.getResourceAsStream("/version.properties")?.use {
                    props.load(it)
                }
                var version = props.getProperty("version", "0.9.37")
                // Strip SNAPSHOT.N suffix: Maven artifact is X.Y.Z-SNAPSHOT (mutable)
                if (version.contains("-SNAPSHOT.")) {
                    version = version.replace(Regex("-SNAPSHOT\\.\\d+$"), "-SNAPSHOT")
                }
                return version
            } catch (_: Exception) {
                return "0.9.37"
            }
        }

        fun toggle(): Boolean {
            enabled = !enabled
            log.info("Sidekick injection ${if (enabled) "enabled" else "disabled"}")
            return enabled
        }

        private fun getOrCreateInitScript(): File? {
            cachedInitScript?.let { if (it.exists()) return it }

            return try {
                val tmpFile = File.createTempFile("dta-sidekick-inject", ".gradle").apply {
                    deleteOnExit()
                    writeText(buildInitScript())
                }
                cachedInitScript = tmpFile
                tmpFile
            } catch (e: Exception) {
                log.warn("Failed to create init script", e)
                null
            }
        }

        private fun buildInitScript(): String {
            val isSnapshot = SIDEKICK_VERSION.contains("SNAPSHOT")
            val snapshotRepo = if (isSnapshot)
                "\n                        maven { url 'https://central.sonatype.com/repository/maven-snapshots/' }"
            else ""
            // Force Gradle to re-check SNAPSHOTs on every build so a new
            // SNAPSHOT publish is picked up without manual cache clearing.
            val cachePolicy = if (isSnapshot)
                """
                configurations.all {
                    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
                }"""
            else ""
            return """
                // Auto-generated by DTA Android Studio Plugin
                beforeSettings {
                    it.dependencyResolutionManagement {
                        repositories {
                            mavenCentral()$snapshotRepo
                        }
                    }
                }
                allprojects {$cachePolicy
                    afterEvaluate {
                        if (plugins.hasPlugin('com.android.application') || plugins.hasPlugin('com.android.library')) {
                            dependencies {
                                debugImplementation 'io.github.yamsergey:dta-sidekick:$SIDEKICK_VERSION'
                            }
                            logger.lifecycle("[DTA] Injected dta-sidekick:$SIDEKICK_VERSION into ${'$'}{project.name} debug build")
                        }
                    }
                }
            """.trimIndent()
        }
    }
}
